[package]
name = "scholar"
version = "0.1.7"
authors = ["Thomas Freeman <tomclaudefreeman@gmail.com>"]
edition = "2018"
description = "A supervised machine learning library."
repository = "https://github.com/thfm/scholar"
readme = "README.md"
license-file = "LICENSE"

# See more keys a